[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
initialization = "CpozUgSwe9FPLy9BLNhY2LTGqLUk1nirUkMMA5RmDw6t"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
